### ISSUE TITLE
What uses the book-level summaries?

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#13]
There are alignments for the [book-level summaries](https://github.com/salesforce/booksum/tree/main/alignments/book-level-summary-alignments). What are these used for? I cannot seem to find a script that uses them.

**Comment by jigsaw2212** [comment]
Hey @dojoteef. We use the test set of the book-level summary alignments for scoring the full-book summaries generated by the different baselines and heuristics in the paper. They are an essential part of the BookSum dataset, and also the most challenging level of granularity since it is hard for any model to read the full book text as input.
