### ISSUE TITLE
Some books on the pinkmonkey are not free now. How to solve this problem?

### ISSUE THREAD

**Issue by GeiduanLiu** [salesforce/booksum#20]
Some books on the pinkmonkey are not free now. How to solve this problem?

**Comment by jigsaw2212** [comment]
Hi @GeiduanLiu. Our scripts collect book summaries from https://web.archive.org/. You shouldn't be facing this problem with any of the books in our dataset from pinkmonkey. Please provide example of a book summary you're trying to access on pinkmonkey.

**Comment by Sotwi** [comment]
@jigsaw2212 I stumbled upon the same issue.
For example: 
[Act II of _Man and Superman_](https://web.archive.org/web/20100116231655/http://pinkmonkey.com/booknotes/monkeynotes/pmManSuperman13.asp) has the following as the page content:

> "You have reached the end of our free MonkeyNotes booknotes for Man and Superman\" by George Bernard Shaw. While the complete MonkeyNote is no longer available online for free, we do offer the complete MonkeyNotes booknotes for this title in a downloadable and printable PDF format in our MonkeyNotes store. Click here to download the complete booknote immediately.

There are other troubling links, for example, [Act III of _Man and Superman_](https://web.archive.org/web/20100116231530/http://pinkmonkey.com/booknotes/monkeynotes/pmManSuperman15.asp) loads a 404 error page. This is unlikely to be solved, the solor coding on the Watback Machine shows this snapshot in orange, which means there was a client-error when the snapshot was taken.

**Comment by jigsaw2212** [comment]
Hi @Sotwi. You are right, there are some pages on web archive that had an error when the snapshot was taken. However, replacing with older links doesn't always work because of redirects, as well as some links (like the one you pointed out) don't have any valid snapshot on web archive - https://web.archive.org/web/2010*/http://pinkmonkey.com/booknotes/monkeynotes/pmManSuperman15.asp 
It's also not possible to manually find the correct snapshot because there might be some other page for that snapshot that might be invalid. Hope that answers the query.
