### ISSUE TITLE
Missing book level alignments, extra chapter level alignments

### ISSUE THREAD

**Issue by bandrus5** [salesforce/booksum#22]
The linked arxiv paper reports that there are 436 book-level alignments, but the `alignments/book-level-summary-alignments/` directory only contains 405 alignments (314 train + 45 val + 46 test). The paper also reports 12,293 chapter-level alignments, but the `alignments/chapter-level-summary-alignments/` directory currently contains 12,630 alignments (9713 train + 1485 val + 1432 test). 

Are there plans to fix these discrepancies? I am trying to reproduce the paper's results with as much fidelity as possible.

**Comment by jigsaw2212** [comment]
@bandrus5 Apologies for getting back to you late on this. The discrepancy in these numbers is because we updated our data collection process to make fetching of data from the links more reliable. We will push an updated version of our paper soon which reflects the new numbers present in the alignment files.
