### ISSUE TITLE
Bugs in sparknotes/get_summaries.py

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#7]
There are a couple of bugs in sparknotes/get_summaries.py:
1. [Line 82](https://github.com/salesforce/booksum/blob/main/scripts/data_collection/sparknotes/get_summaries.py#L82) can lead to a crash if the span cannot be found. It should probably get moved into the try/except block above on [line 76](https://github.com/salesforce/booksum/blob/main/scripts/data_collection/sparknotes/get_summaries.py#L76).
2. On [line 128](https://github.com/salesforce/booksum/blob/main/scripts/data_collection/sparknotes/get_summaries.py#L128), you should probably continue if there are no section paragraphs, i.e. no summary.

**Comment by jigsaw2212** [comment]
During the testing of the script [Line 82](https://github.com/salesforce/booksum/blob/main/scripts/data_collection/sparknotes/get_summaries.py#L82) doesn't crash for any of the web archive links. However, since the web archive servers are not as reliable, I've added some extra error handling for this line too. Suggestion incorporated for line 128.
